# Generated by Django 3.2.4 on 2022-12-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpaymenthandler',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
