# Generated by Django 3.2.4 on 2022-12-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stockpaymenthandler_is_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedlog',
            name='outboundRef',
        ),
        migrations.AddField(
            model_name='closedlog',
            name='pforef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.outboundstockhandler'),
        ),
        migrations.AddField(
            model_name='closedlog',
            name='pfpref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.stockpaymenthandler'),
        ),
    ]
