# Generated by Django 3.2.4 on 2022-12-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221205_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='can_rollback',
            field=models.BooleanField(default=False),
        ),
    ]
