# Generated by Django 3.2.4 on 2022-12-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service_can_rollback'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundstockhandler',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockpaymenthandler',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
