# Generated by Django 3.2.4 on 2022-12-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221206_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='msrp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
