# Generated by Django 3.2.4 on 2022-12-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20221206_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='msrp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
